# Generated by Django 5.2.4 on 2025-08-04 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_grade_user_grade_graded_by_grade_graded_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='graded_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_recived', to=settings.AUTH_USER_MODEL),
        ),
    ]
