# Generated by Django 5.2.4 on 2025-08-04 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_submission_submit_by_alter_grade_graded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submit_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
