# Generated by Django 5.2.4 on 2025-08-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_submission_submit_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), (None, 'NoRole')], max_length=15),
        ),
    ]
