# Generated by Django 5.2.4 on 2025-08-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to='profile_photo'),
        ),
    ]
